default: &default
  adapter: postgresql
  database:  <%= ENV['POSTGRES_DATABASE'] %>
  username: <%= ENV['POSTGRES_USER_NAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rinha_development

test:
  <<: *default
  database: rinha_test

production:
  <<: *default
  database: rinha_production
